### ISSUE TITLE
a wrong example code

### ISSUE THREAD

**Issue by lqlv2** [eh3rrera/project-reactor-course#1]
in this article: https://eherrera.net/project-reactor-course/04-using-other-reactive-operators/aggregating-flux.html
the demo code for the Flux.collectMap() function is replaced by the  Flux.collectMultiMap() function

**Comment by eh3rrera** [comment]
Hi @LeQuiLong7!

You're right, thank you so much!

Instead of using:
```java
Mono<Map<Integer, Collection<Integer>>> monoMap =
    integerFlux.collectMultimap(
            i -> i / 10,
            i -> i % 10
    );
```

It should be:
```java
Mono<Map<Integer, Integer>> monoMap = 
    integerFlux.collectMap(
                i -> i / 10,
                i -> i % 10
    );
```

I've made the change. Thanks again!
