### ISSUE TITLE
some confusion

### ISSUE THREAD

**Issue by lqlv2** [eh3rrera/project-reactor-course#2]
in this article about context "https://eherrera.net/project-reactor-course/07-using-a-context/the-problem-context-solves.html"
at the very end: "A Context is a key/value store (like a [Map]) that allows us to store data associated with a particular **Publisher** rather than a particular thread (like ThreadLocal does)."

but in later article "https://eherrera.net/project-reactor-course/07-using-a-context/writing-reading-context.html"
at the very beginning: "As I mentioned before, a Context is populated at subscription time, one Context for each **Subscriber**. This way, all the operators upstream in the chain will have access to it."

i think it may be a confusion between Publisher and Subscriber here

**Comment by eh3rrera** [comment]
Yes, the first statement is misleading. I've replaced `Publisher` with `Subscriber`.
